name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  ci_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck

  deploy_dev:
    runs-on: ubuntu-latest
    needs: ci_check

    steps:
      - name: Connect to server and deploy changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ~/projects/yandex-backend
            git pull
            source ~/.bashrc
            yarn
            yarn lint
            yarn typecheck
            yarn restart
